### Numpy

#### Python Libraries
- Numpy
- Pandas
- Matplotlib
- Seaborn
- SciKit learn

#### Numpy(Numerical Python)
- Numpy is used to create multi dimensional arrays 
- used to mathimatical computations faster

#### How to install numpy and import


- pip install numpy
- conda install numpy

In [1]:
import numpy as np

In [2]:
#Version
np.__version__

'1.15.4'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolute', 'ab

**How to create numpy array**

- List Tuple

In [5]:
li=[2,3,4,5]
type(li)
print(li)

[2, 3, 4, 5]


In [8]:
a=np.array([2,3,4,5,6])
a
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(a.ndim)   #dimension of array
print(a.itemsize)  # memory allocated to each element in bytes
print(a.nbytes)
print(a.size)

1
4
20
5


In [15]:
#2-d array Syntax
#[[row1],[row2],[row3].....[rown]]

In [18]:
b=np.array([[2,3,4,5],[5,6,7,8],[12,34,56,78]])
b

array([[ 2,  3,  4,  5],
       [ 5,  6,  7,  8],
       [12, 34, 56, 78]])

In [21]:
print(b.ndim)
print(b.shape) #rows and columns
print(b.size)

2
(3, 4)
12


In [22]:
#Multi dimensional array
#[[[row1],[row2],[row3].....[rown]]]


In [26]:
c=np.array([[[12,23,45,15],[3,4,5,6],[7,8,9,10]]])
print(c)
print(c.ndim)
print(c.shape)

[[[12 23 45 15]
  [ 3  4  5  6]
  [ 7  8  9 10]]]
3
(1, 3, 4)


#### Why numpy

In [27]:
li=[2,3,4,5]
print(li)

[2, 3, 4, 5]


In [28]:
a=np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [29]:
li+5

TypeError: can only concatenate list (not "int") to list

In [30]:
a+5

array([ 7,  8,  9, 10])

#### Numpy methods
- np.arange()
- np.linspace()
- np.zeros()
- np.ones()
- Reshape
- Statistical methods
- random methods

In [32]:
# for loop
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [33]:
range(1,10)

range(1, 10)

In [38]:
a=np.arange(1,10)
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1


In [40]:
b=np.arange(1,20,3)  #(start,stop,step)
b

array([ 1,  4,  7, 10, 13, 16, 19])

**linspace()**

In [41]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [42]:
8.57894737 -  8.10526316

0.47368421000000005

In [43]:
6.68421053-6.21052632

0.47368421000000005

In [44]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [47]:
np.linspace(1,10,15,retstep=True)

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
         4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
         7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]),
 0.6428571428571429)

**ones()**

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.ones([3,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

**Reshape**
- to change shape

In [63]:
a=np.array([[2,3,4],[5,6,7],[9,4,7]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[2 3 4]
 [5 6 7]
 [9 4 7]]
2
9
(3, 3)


In [ ]:
3 rows * 3 col =9
1 row  * 9 col =9
9 rows * 1 col =9

In [65]:
a.reshape(1,9)
a.reshape(9,1)

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [9],
       [4],
       [7]])

In [67]:
a=np.array([2,3,4,5])
a.dtype

dtype('int32')

In [68]:
a=np.array([1.5,3,4,5])
a.dtype

dtype('float64')

In [72]:
d=np.array([23,25,46,4.5,'num'])
d.dtype   #char data type

dtype('<U32')

In [73]:
a

array([1.5, 3. , 4. , 5. ])

In [74]:
a=np.array([[2,3,4],[5,6,7],[9,8,7]])
print(a)

[[2 3 4]
 [5 6 7]
 [9 8 7]]


In [78]:
np.max(a)
np.min(a)
np.argmax(a) #max value index position
np.argmin(a)

0

In [81]:
np.sum(a)
np.mean(a)
np.median(a)

6.0

In [86]:
np.log(10)
np.log10(10)
np.sin(3.14/2)
np.tan(3.14)
np.cos(3.14/4)

0.7073882691671998

In [87]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [89]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [91]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
c=np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
c[2]
c[1]

array([4, 5, 6])

In [101]:
c[2][1]
c[1][0:1]

array([4])

In [167]:
a=np.array([2,3,4,5],ndmin=10)
a

array([[[[[[[[[[2, 3, 4, 5]]]]]]]]]])

In [122]:
np.logspace(1,10,9)

array([1.00000000e+01, 1.33352143e+02, 1.77827941e+03, 2.37137371e+04,
       3.16227766e+05, 4.21696503e+06, 5.62341325e+07, 7.49894209e+08,
       1.00000000e+10])

In [184]:
np.random.randint(1,10,(2,3,3,2,2))

array([[[[[3, 3],
          [4, 3]],

         [[3, 1],
          [3, 4]],

         [[8, 9],
          [2, 5]]],


        [[[4, 5],
          [1, 8]],

         [[2, 3],
          [7, 4]],

         [[2, 6],
          [6, 7]]],


        [[[8, 1],
          [7, 8]],

         [[7, 6],
          [6, 8]],

         [[5, 8],
          [2, 1]]]],



       [[[[1, 6],
          [3, 8]],

         [[5, 9],
          [5, 6]],

         [[4, 5],
          [1, 3]]],


        [[[3, 4],
          [1, 5]],

         [[1, 5],
          [8, 9]],

         [[3, 1],
          [3, 7]]],


        [[[4, 2],
          [8, 4]],

         [[3, 8],
          [9, 8]],

         [[7, 3],
          [2, 5]]]]])

In [185]:
a=np.random.randint(1,10,15).reshape(3,5)
a

array([[3, 4, 6, 6, 7],
       [2, 6, 9, 4, 4],
       [2, 6, 5, 6, 3]])

In [138]:
a1=np.random.randn(6)
a1

array([ 0.23720591, -1.35285578,  0.19086499,  0.10680825, -0.15148138,
       -1.34723627])

In [146]:
a2=np.random.random(5)
a2

array([0.24215722, 0.72859858, 0.6055549 , 0.18270721, 0.89453988])

In [187]:
a=np.arange(11,20).reshape(3,3)
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [188]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
a*b

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [160]:
a+b
a-b
a@b

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [190]:
a>6

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [162]:
a[a>6].sum()

135

In [163]:
a.dot(b)

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [194]:
m=np.array([[2,3,4],[5,6,7],[9,8,7]])
m

array([[2, 3, 4],
       [5, 6, 7],
       [9, 8, 7]])

In [193]:
m.max(1)

array([4, 7, 9])

In [195]:
m.max(0)

array([9, 8, 7])

In [196]:
m.transpose()

array([[2, 5, 9],
       [3, 6, 8],
       [4, 7, 7]])

In [205]:
np.flip(m)   #reverse matrix

array([[9, 8, 7],
       [7, 6, 5],
       [4, 3, 2]])

## Pandas
- Used for Data Manipulation and Data Analysis
- Types of Data Structures:
    - Series
        - one dimensional representation
        - pd.Series(Sequence)
    - DataFrames
        - Two dimensional representation of data
        - pd.DataFrame()
        
[Pandas Official Website](https://pandas.pydata.org/)